Add timeouts to SDK config
permitio/permit-python pull request #69
Opened 2024-04-14 15:58 UTC by obsd

2024-04-14 16:01 UTC, omer9564 commented on permit/config.py
> +        DEFAULT_TIMEOUT,
Do we really want to have default value ? Currently there is no value set for timeout this is can change behavior

2024-04-15 15:51 UTC, obsd commented on permit/config.py
> +DEFAULT_TIMEOUT = 60 * 5  # 5 minutes
this is the default, but I've removed it

2024-04-15 15:51 UTC, obsd commented on permit/config.py
> +        DEFAULT_TIMEOUT,
removed

2024-04-18 08:52 UTC, omer9564 requested changes
Few mostly semantic comments, pre-commit and snyk check is failing

2024-04-18 08:52 UTC, omer9564 commented on permit/api/base.py
> +    def __init__(self, client_config: dict, base_url: str = "", timeout: Union[int, None] = None):
Optional[int] instead of Union[int,None]

2024-04-18 08:52 UTC, omer9564 commented on permit/enforcement/enforcer.py
> +            timeout_config = {"timeout": ClientTimeout(total=self._config.pdp_timeout)}
why overwrite the entire dict instead of doing timeout_config["timeout"] = ...

2024-04-18 08:52 UTC, omer9564 commented on permit/enforcement/enforcer.py
> +            timeout_config = {"timeout": ClientTimeout(total=self._config.pdp_timeout)}
same comment here

2024-04-18 08:52 UTC, omer9564 commented on permit/enforcement/enforcer.py
> +            timeout_config = {"timeout": ClientTimeout(total=self._config.pdp_timeout)}
would extract this to some property because you use it twice and will probably use it many more times in the future

2024-04-18 08:52 UTC, omer9564 commented on requirements-dev.txt
> +pytest_httpserver
missing new line in the end of file

2024-04-18 08:52 UTC, omer9564 commented on .gitignore
> +.idea/
missing new line in the end of the file

2024-04-18 08:52 UTC, omer9564 commented on .gitignore
> +.idea/
do you really need both .idea and .idea/ ?

2024-05-05 14:21 UTC, omer9564 approved these changes

2024-05-05 14:28 UTC, merged